name: Auto-add to project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    name: Add to project board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/gitrdunhq/projects/${{ github.event.repository.name == 'firka' && '1' || github.event.repository.name == 'wfc' && '2' || github.event.repository.name == 'eedom' && '3' || '4' }}
          github-token: ${{ secrets.PROJECT_TOKEN }}
